
services:
  db:
    image: postgres:17
    container_name: tg_task_bot_db
    restart: always
    env_file:
      - .env
    volumes:
      - bot_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tg_task_tracker"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s

  bot:
    build: .
    container_name: tg_task_bot
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

    command: python -m app.main

  
    
volumes:
  bot-db-data: